version: "3.4"

services:
  web-app:
    # image: nginx:alpine
    build:
      context: ./WebApp/persa-learn
      dockerfile: Dockerfile.prod
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # - ./WebApp/persa-learn/build:/web
    environment:
      - NODE_ENV=production

    restart: always
    # environment:
    #   - apiAdd=value
    # build:
    #   context: ./WebApp/persa-learn
    #   dockerfile: Dockerfile.prod
    # ./WebApp/persa-learn
    ports:
      - "3000:3000"
    # dockerfile: ./WebApp/persa-learn/Dockerfile
  api:
    build:
      context: ./node js RESTful API
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start
