FROM node
WORKDIR /app
COPY package.json /app
RUN echo "env: $NODE_ENV"

ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
        else npm install --omit=dev; \
        fi

COPY . /app
EXPOSE 8080
CMD ["npm","run","dev"]
# CMD ["npm","start"]